# Generated by Django 4.1.4 on 2022-12-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrigeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
                ('date_input', models.CharField(max_length=50, null=True)),
                ('date_add_frige', models.CharField(max_length=50, null=True)),
                ('freezing', models.CharField(max_length=50, null=True)),
                ('date_expire', models.CharField(max_length=50, null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('source', models.CharField(max_length=200, null=True)),
                ('etc', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
