# Generated by Django 4.1.4 on 2022-12-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frige', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frigeitem',
            name='quantity',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
