# Generated by Django 4.1.4 on 2023-01-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NoticeItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=50)),
                ("date_input", models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
