# Generated by Django 4.1.4 on 2023-01-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notice", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="noticeitem",
            name="context",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="noticeitem",
            name="date_input",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
